### ISSUE TITLE
Support for Symfony 4

### ISSUE THREAD

**Issue by hanishsingla** [bestit/flagception-bundle#24]
Do you have any plans for Symfony 4. I can see few depreciation in this bundle and can contribute towards it.

**Comment by migo315** [comment]
Thanks for you issue. We will release a new major version this weekend, which supports Symfony 4 (and travis will test against it)

The new release (3.x) is a complete revised version. ;-)

**Comment by hanishsingla** [comment]
Great Thanks .. Hope I will be able to migrate to Symfony 4 finally then :-)

**Comment by migo315** [comment]
Sorry, I need another day for finish the new release. Found some bugs yesterday ;-)

**Comment by migo315** [comment]
Version 3.0 is released now. My tests with Flex and Symfony 4 was successful. 

Please consider that the hole project was renamed to `Flagception`. The package also: https://packagist.org/packages/flagception/flagception-bundle

Don't hesitate to contact me if you have questions or suggestions for improvements ;-)

**Comment by migo315** [comment]
@hanishsingla Was the migration successful?

**Comment by hanishsingla** [comment]
@migo315 .. Yes, it is working fine as expected. Thanks for new features 👍 

However we hit another obstacle. Assetic is replaced by Webpack in SF4 and our template is not webpack compatible. Checking for other options for it :(
