### ISSUE TITLE
Deprecation notice with Symfony 4.4

### ISSUE THREAD

**Issue by bretrzaun** [bestit/flagception-bundle#61]
When using the bundle in a Symfony 4.4 application this deprecation notice appears:
> Using short factory syntax for service "flagception.expression_language" is deprecated since Symfony 4.4, use "['@flagception.factory.expression_language_factory', 'create']" instead.

**Comment by migo315** [comment]
Thanks for the hint. I will check all deprecation messages this week and make the bundle fit for 5.0.

**Comment by migo315** [comment]
Fix in currenty master.

**Comment by bretrzaun** [comment]
Can you please create a release for this change?

**Comment by migo315** [comment]
Released under 3.3 with support for Symfony 5.

If you have any questions or trouble, just reopen this issue. ;-)
