### ISSUE TITLE
Support for Twig 3.

### ISSUE THREAD

**Issue by mssimi** [bestit/flagception-bundle#69]
Hey, are there any future plans to add support for Twig 3?

Thx.

**Comment by migo315** [comment]
Yes of course. I don’t think there any big changes needed. I will check it soon.

**Comment by migo315** [comment]
I've created a branch which should support twig3. Maybe you can test it, @mssimi? 

feature/support-twig3

**Comment by migo315** [comment]
@mssimi The Bundle version 3.5.0 has Twig 3 support now! 

Let me know if something doesn't work.
