### ISSUE TITLE
Symfony 6.0 support

### ISSUE THREAD

**Issue by amacrobert-meq** [bestit/flagception-bundle#90]
Flagception does not list compatibility with Symfony 6.0.

I'm not seeing any deprecation messages when running flagception-bundle 4.1 on Symfony 5.4, so it probably doesn't need any code changes -- just a composer tweak.

This is the error I get when trying to update to Symfony 6.0 in a project that uses flagception-bundle:

```
$ composer update
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires flagception/flagception-bundle ^4.1 -> satisfiable by flagception/flagception-bundle[4.1.0].
    - flagception/flagception-bundle 4.1.0 requires symfony/dependency-injection ^4.4 | ^5.0 -> found symfony/dependency-injection[v4.4.0-BETA1, ..., v4.4.34, v5.0.0-BETA1, ..., v5.4.0] but these were not loaded, likely because it conflicts with another require.
```

**Comment by mssimi** [comment]
This bundle seems dead to me, is it?

**Comment by migo315** [comment]
I'm so sorry. Since I changed to another company, I don't have access to this repository anymore.

@mKnoop @avareldev Can you check check and approve the open pr?

**Comment by avareldev** [comment]
Looking into it next year!

**Comment by mssimi** [comment]
@avareldev Is it rather beginning of the year or end? :)

**Comment by gellis** [comment]
@avareldev Any update on this?

**Comment by mKnoop** [comment]
Sorry for the late reply.

We will check the pr next week and try to schedule this for the next release.
