### ISSUE TITLE
Flagception psr cache compatibility

### ISSUE THREAD

**Issue by D3vJ3rry** [bestit/flagception-bundle#94]
Flagception is not compatible with psr cache 2 | 3 
The main repo has a pr from last year which has never been merged... 
Are you guys looking for maintainers ?
https://github.com/bestit/flagception-sdk/pull/30
can someone please apprive that PR ?
@migo315 @ajgarlag @Haehnchen @0x346e3730 @RedactedProfile

**Comment by mKnoop** [comment]
Sorry for the late reply.

We will check the mentioned pr next week and try to schedule this for the next release.

**Comment by mKnoop** [comment]
We have released a new version for this. It should now be compatible with psr cache 2 and 3
